export const SALES_ADD_ITEM = 'SALES_ADD_ITEM';
export const SALES_REMOVE_ITEM = 'SALES_REMOVE_ITEM';

export const SALES_CATEGORY_CHANGE = 'SALES_CATEGORY_CHANGE';
export const SALES_ITEM_NAME_CHANGE = 'SALES_ITEM_NAME_CHANGE';
export const SALES_ITEM_QTY_CHANGE = 'SALES_ITEM_QTY_CHANGE';
export const SALES_ITEM_RATE_CHANGE = 'SALES_ITEM_RATE_CHANGE';
